groups:
- name: main
  jobs:
  - base-image-job

resource_types:
- name: base-image-resource
  type: docker-image
  source:
    repository: bappy776/base-image
    tag: latest

resources:
- name: slack
  type: slack-notification
  source:
    url: {{cfee_audit_slack_url}}
- name: daily-10am
  type: cron-resource
  source:
    expression: "0 10 * * *"
    location: "America/New_York"
    access_token: {{cfaas_github_token}}

jobs:
  - name: base-image-job
    public: true
    plan:
    - in_parallel:
      - get: daily-10am
        trigger: true
      - get: base
      - get: slack
    - task: base-image-task
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {bappy776:base-image}
          run:
            path: pwd
            
