---
resources:
# The repo with our Dockerfile
- name: concourse-base-image
  type: git
  icon: github
  source:
    uri: https://github.com/bappy776/concourse-base-image.git
    branch: main

# Where we will push the image to
- name: base-image
  type: registry-image
  icon: docker
  source:
    repository: ((image-repo-name))/base-image
    username: ((registry-username))
    password: ((registry-password))

jobs:
- name: build-and-push
  plan:
  - get: concourse-base-image
  - task: build-task-image
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: bappy776/base-image
      inputs:
      - name: concourse-base-image
      outputs:
      - name: image
      params:
        CONTEXT: concourse-base-image
      run:
        path: build
  - put: base-image
    params:
      image: image/image.tar